# Site settings
title: Chá dos Noivos - Fernanda e Icaro
email: ic.nanda@icloud.com
url: icaroefernanda.party
description: "17/02/2017 será um dos momentos mais felizes das nossas vidas e queremos fazer um esquenta com vocês no dia 11/02!!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Icaro e Fernanda Wedding

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: https://twitter.com/SBootstrap
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
